#pragma once

#define STRINGIFY_(v) #v
#define STRINGIFY(v) STRINGIFY_(v)

#define CXADC_VHS_SERVER_VERSION STRINGIFY(CXADC_VHS_SERVER_MAJOR) "." STRINGIFY(CXADC_VHS_SERVER_MINOR) "." STRINGIFY(CXADC_VHS_SERVER_PATCH)
